version: "3.9"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
    restart: always
  backend:
    depends_on:
      - database
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_URL: database:3306/homestead
    build: backend
    ports:
      - "8888:8888"
    restart: always
  frontend:
    build: frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "9099:9099"
